### ISSUE TITLE
fix https / http issue

### ISSUE THREAD

**Issue by seegerseeger** [openbudgets/openbudgets.github.io#11]
Currently, visiting openbudgets.eu with https in the address bar results in an 'Your connection is not private' error.

**Comment by pwalsh** [comment]
hmm, this is old. it was never drawn to my attention ( at least not for 12 months :) ), and I will fix it now.

**Comment by pwalsh** [comment]
@seegerseeger I've fixed this at the DNS/proxy level. it should start working today. Can you check in Germany around lunch time and let me know if you see that https now works.
