### ISSUE TITLE
Ordered lists disabled

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/openbudgets.github.io#13]
The CSS used by the site disables numbering of ordered lists. Due to the [base styles for lists](https://github.com/openbudgets/openbudgets.github.io/blob/master/_sass/base/_lists.scss#L3) `ol` is set to `list-style-type: none;`. While I can understand this for layout purposes, it would be useful to be able to produce numbered lists in body text.

**Comment by seegerseeger** [comment]
@cecilaki, could you help out here? Thanks
