### ISSUE TITLE
Blog improvements

### ISSUE THREAD

**Issue by seegerseeger** [openbudgets/openbudgets.github.io#18]
the first sentence of a blogpost (until first linebreak) currently automatically becomes the ‘abstract’ sentence of that post in the blogpost overview (http://openbudgets.eu/blog/). Could this be changed so that you can define an ‘abstract’ when composing the blogpost? 
could the ‘image’ specified in blogpost be featured in the post as well? similar to https://okfn.de/blog/2016/03/sehrgutachten/

**Comment by smth** [comment]
You can already define the excerpt manually, as has been done here for example: https://github.com/openbudgets/openbudgets.github.io/blob/master/_posts/2016-07-20-comparing-money-across-time-and-space.md

Yes, image could be automatically added to the start of the post if you like. This would however be slightly less flexible than the current solution of adding it manually. You'd probably also want to go back and remove all the manually added images.

**Comment by smth** [comment]
Is this something you'd like me to implement @seegerseeger ?

**Comment by annafralberts** [comment]
I like the manual input. That should work.

**Comment by smth** [comment]
OK. I'll close this issue.
