### ISSUE TITLE
glitch in text format

### ISSUE THREAD

**Issue by elisalindinger** [openbudgets/openbudgets.github.io#19]
In [deliverables,](http://okfnlabs.org/openbudgetseu-staging/about/deliverables/) WP 3, the file size is bold

**Comment by smth** [comment]
It looks like that page is markdown, so if that bolding is unwanted, you should remove the [wrapping asterisks](https://raw.githubusercontent.com/openbudgets/openbudgets.github.io/master/about/deliverables.md).

**Comment by annafralberts** [comment]
Will do
