### ISSUE TITLE
Side-Bar

### ISSUE THREAD

**Issue by annafralberts** [openbudgets/openbudgets.github.io#20]
Going through all the mock-ups and comments I would propose that the side bar should feature:
1. News
2. Stay in the loop
3. Twitter feed

**Comment by smth** [comment]
The first two are already present (some blog posts need to be given the "news" category for that section to appear.

It says [here](https://github.com/openbudgets/openbudgets.github.io/issues/10#issuecomment-235869636) that the Twitter feed is no longer wanted. Could you confirm which instruction to follow?

**Comment by annafralberts** [comment]
I will double check with Bela

**Comment by annafralberts** [comment]
Couldn't reach Bela, so I say YES to twitter :)

**Comment by annafralberts** [comment]
@seegerseeger ?? Comments?

**Comment by smth** [comment]
OK. I've sent you an email explaining what I need from you guys for this.

**Comment by smth** [comment]
Twitter feed is now on the staging site http://okfnlabs.org/openbudgetseu-staging/

**Comment by annafralberts** [comment]
Top! Thanks
