### ISSUE TITLE
Logo + Header Color

### ISSUE THREAD

**Issue by annafralberts** [openbudgets/openbudgets.github.io#21]
They are just a different type of green (checked it with different people and different screens)
<img width="625" alt="screen shot 2016-08-11 at 14 07 08" src="https://cloud.githubusercontent.com/assets/12712917/17590875/e317b536-5fdb-11e6-988b-e7f25078cfd4.png">
The previous version had a nice play on the gray-green theme: 
![screen shot 2016-08-11 at 15 34 58](https://cloud.githubusercontent.com/assets/12712917/17590886/eecd02b4-5fdb-11e6-99f6-5a39829630b0.png)

Maybe you can adjust it with something along those lines.

Tagline can be left unchanged for now.

**Comment by smth** [comment]
Yeah, there a few slightly different shades there, which should in theory be the same:
- Banner background colour
- Image background colour
- Image foreground colour

Nothing has changed in this respect (though it's possibly more noticeable now), it's the same image and the same background colour.

I can attempt to match all these colours. Is that what you are asking me to do?

**Comment by annafralberts** [comment]
Can you show me an example of how that would look?
And maybe an ajdusted version of the second screenshot for the new page?

**Comment by smth** [comment]
I've updated the staging site (with a transparent image), so you can see it there @annafralberts

**Comment by annafralberts** [comment]
Yup, saw it. Much bettter
