### ISSUE TITLE
Mobile view stuff

### ISSUE THREAD

**Issue by annafralberts** [openbudgets/openbudgets.github.io#23]
- social media buttons too close together
  - Careful with twitter stream that scrolls (should not fit entire screen)

**Comment by smth** [comment]
Are you referring to these icons?

![social](https://cloud.githubusercontent.com/assets/1375708/17658953/208054d0-62c7-11e6-8811-58526365114f.jpg)

They don't look too close together to me.

**Comment by annafralberts** [comment]
Yes

**Comment by smth** [comment]
You want more space between them horizontally?

**Comment by smth** [comment]
Done.

(If we implement a Twitter feed, I'll do it in a way that doesn't require scrolling.)
