### ISSUE TITLE
Events.yaml Adjustment

### ISSUE THREAD

**Issue by annafralberts** [openbudgets/openbudgets.github.io#24]
Can you adjust the events.yaml:

Old
Title:
date:
status:
description:
link:

to new
Title:
date:
       from: dd-mm-yy
       to: dd-mm-yy
status:
description:
link:

**Comment by smth** [comment]
Do you also want some changes reflected in the template? i.e is this something I'm required for? (It looks like currently the date field is not being shown on the front-end)

Could you explain how the `date` field would be used, in conjunction with the `from` and `to` fields.  The former seems redundant here.

**Comment by annafralberts** [comment]
Yes, I made this an issue, so that it can be changed in the template. It allows us to put in multi-day events and sort easier.

**Comment by smth** [comment]
So, if you want to use both type of date formats in the yaml, I could add the `to` and `from` entries to the events listing template, if the the `date` entry is not present. Is that how you are imagining it working?

**Comment by annafralberts** [comment]
Right. The to and from were in my view when I pasted it sub-fields of date.

**Comment by smth** [comment]
That will work now, though the format will have to be slightly different to the one you suggested. I've added an example [here](https://github.com/okfn/openbudgetseu-staging/blob/gh-pages/_data/events.yml#L9-L10). The dates are displayed [here](http://okfnlabs.org/openbudgetseu-staging/events/).
