### ISSUE TITLE
Improve the resource list page

### ISSUE THREAD

**Issue by cecilaki** [openbudgets/openbudgets.github.io#4]
At the moment it's pretty simple and not very appealing + there's a vert big difference with the [Events page](http://openbudgets.eu/events/)

============= Current

[<img width="621" alt="capture d ecran 2015-10-21 a 12 28 06" src="https://cloud.githubusercontent.com/assets/6681719/10635252/40da3e3a-77ef-11e5-92e0-356924f0a562.png">](http://openbudgets.eu/resources/)

============= Possible to improve this list by adding:
- a resized featured image (taken from the post)
- a category (to define in the resource template)
- a bigger title 
- a short description (to define while writing the post)
- a read more button

============= Example

<img width="833" alt="capture d ecran 2015-10-21 a 12 40 54" src="https://cloud.githubusercontent.com/assets/6681719/10635503/2088d810-77f1-11e5-852b-128eaf874881.png">

**Comment by smth** [comment]
@cecilaki yup, this was very much unfinished. I have now added content and styling, guided by your requests: http://openbudgets.eu/resources/

Note: This and the blog page currently share styling.

**Comment by cecilaki** [comment]
@smth that is really wonderful ! Thank you so much! I love it :)
