### ISSUE TITLE
No markdown support in blogpost preview

### ISSUE THREAD

**Issue by seegerseeger** [openbudgets/openbudgets.github.io#40]
Markdown not supported in preview view under /blog: 
![screen shot 2016-11-22 at 11 28 19](https://cloud.githubusercontent.com/assets/9677965/20520376/d169eab8-b0a6-11e6-9b66-87a6ef25dd5a.png)

It does, however, work on the landing page: 
![screen shot 2016-11-22 at 11 27 01](https://cloud.githubusercontent.com/assets/9677965/20520339/add403e0-b0a6-11e6-8eac-bbc7a98f556e.png)

**Comment by pwalsh** [comment]
@smth can you fix this with the new design elements pls/

**Comment by smth** [comment]
Done here https://github.com/openbudgets/openbudgets.github.io/commit/359dea58f20515c96210c53b2aedb7059a17de2e
