### ISSUE TITLE
Final Platform Design / Visual Integration

### ISSUE THREAD

**Issue by seegerseeger** [openbudgets/openbudgets.github.io#44]
As communicated with the consortium, here are the design mockups for the final OBEU platform. It is a redesign based on the current design of http://openbudgets.eu. From these mockups, a basic styleguide has been created, to be found **[here](https://docs.google.com/document/d/1nvos7pyJeD28dVBOPcP8TC0L2csyH3PvkcUya7KYlf4/edit?usp=sharing)**.

---

**Landing Page**

![landing page](https://user-images.githubusercontent.com/9677965/26936051-d8be6812-4c6d-11e7-8805-12c568eef16a.png)

Changes: 
- New header section: 'Explore Data' (depending on ongoing tech discussions, this will most likely lead to the Data Explorer built into Indigo, from which the various OBEU tools can be launched)
- New header section: Data Toolbox (see mockup below for details)
- New header section: Documentation (will lead to a PDF containing documentation, to be delivered by OKF DE)
- Overview over tools in three parts: 'Are you a...?', clicking the headline will lead to the 'Data Toolbox' page with the corresponding filter enabled (see Data Toolbox screenshot)
- Section 'Get to know new ways..' displays two most recent blogposts 
- Teaser of 'About' Section below

----

**Data Toolbox Page** 

This section is essentially a gallery of the tools, stories, and prototypes produced in the course of the project. Each tool has an icon, a call-to-action button leading to the tool, and in some cases, a link with instructive materials (such as screencasts etc). Some of the icons are still yet to be produced, so in some cases there will be placeholders. This is the only interactive part of the website that needs to be built, as it has three filters: 
1) Filter by Audience: Administration, Data Wrangling, Journalism
2) Filter by Tool, Prototype, Story, Game

![toolbox](https://user-images.githubusercontent.com/9677965/26937454-b1988868-4c71-11e7-8038-14c79904bf6d.png)

---

**Upload Page**

Depending on the tech-partners, there may be an upload section leading to an OpenBudgets version of the OS packager featured in the header, but this has yet to be decided. For now, the following 'How to Upload' page is simply a manual with screenshots:

![upload page - basic](https://user-images.githubusercontent.com/9677965/26936747-c3dd625c-4c6f-11e7-90ab-254359d2f461.png)

---

**Blog**

The Blog will stay mainly as is, with a few minor adjustments. 

![blog](https://user-images.githubusercontent.com/9677965/26938284-11a5674c-4c74-11e7-98e8-bff58260e4b2.png)

**Comment by pwalsh** [comment]
@smth please review and add any comments here.

**Comment by smth** [comment]
I don't want to interfere too much at this stage. Design wise I would perhaps question the readability of 
![about-open-budgets](https://user-images.githubusercontent.com/1375708/27026020-524b2678-4f54-11e7-83f8-3b6356bd9e0b.jpg)

Though I think this could be improved without disrupting the design too much.

In terms of the new functionality, has there been any discussion about how the filtering will be implemented? I assume the preference is for the site to remain static. This could probably be done with something like [Isotope](https://isotope.metafizzy.co/). I say probably because I don't have much experience with it, so not sure for example if/how it could filter by two facets at a time.

Where can the design files and/or code be found for these designs?

**Comment by pwalsh** [comment]
@smth 

The only design files are the pngs. Do you mean the format that was used, like the photoshop files? @seegerseeger if you have them, pls supply.

Yes, the site must remain static and basically be as simple as possible. One of our devs at OKI can specifically help on the multiple filtering implementation.

**Comment by smth** [comment]
Yes, Photoshop, Illustrator, Affinity etc. Particularly important will be vector versions of the icons/illustrations (which if not part of the main file, can be supplied separately). Likewise for the new logo.

**Comment by seegerseeger** [comment]
Hi @smth, the mockups have been made with sketch, I have exported them to Zeplin and just sent you an invite. If you prefer, I can send you the sketch file as well if that helps, let me know!

**Comment by smth** [comment]
Thanks @seegerseeger Yes, please send me the Sketch files too.

**Comment by seegerseeger** [comment]
I've sent you the sketch & svg file of the mockups. The new logo is attached as an svg to this post. as for the icons, you can use the ones that already are there and put placeholders for the rest. Let me know if we can help! Isotope looks like it does the job, just keep in mind that we have two filtering parameters (audience and type), perhaps [this](https://codepen.io/desandro/pen/owAyG) would do?
 
[openbudgets-logo-new.eps.zip](https://github.com/openbudgets/openbudgets.github.io/files/1067818/openbudgets-logo-new.eps.zip)

**Comment by DianaMPG** [comment]
@smth do you already have an estimate of how long the implementation will take?

**Comment by smth** [comment]
@DianaMPG 3-4 days

**Comment by DianaMPG** [comment]
perfect thanks @smth

**Comment by smth** [comment]
This is all done. See https://github.com/openbudgets/openbudgets.github.io/compare/final-platform-design

**Comment by pwalsh** [comment]
@smth can you deploy it somewhere so we can look?

**Comment by smth** [comment]
Here you go http://okfnlabs.org/openbudgets.github.io/

**Comment by pwalsh** [comment]
thank you @smth

**Comment by DianaMPG** [comment]
thanks @smth it looks great. 

I have a minor change request so far: 
Could you move "Get to know new ways to discover and share fiscal datasets." entirely into the grey background?

**Comment by smth** [comment]
I certainly could. That's how it is in the design though (and presumably signed off as such), so I'd like to double check with the designer.

**Comment by skarampatakis** [comment]
Filter dropdowns do not close after selection. Is this by design?

**Comment by seegerseeger** [comment]
Thank you @smth, rapidly executed, looks great, ad the .js for the toolbox works great as well! 
A few minor adjustments: 
- if e.g. the 'audience' filter is selected, and there is no 'type:Stories', could 'type:Stories' be greyed out / removed automatically?
- if a menu option in the header is selected, could you remove the black outline box and instead apply the hover animation in green? like so: 
![button](https://user-images.githubusercontent.com/9677965/27279699-bb5e7476-54e5-11e7-9064-df1386fa17b9.png)
- as @skarampatakis said, could you make the filter dropdowns close after selection?
- on the 'Upload' page, could the images be  enlargeable by clicking? 
- some of the tools have false tags, I'll go through them and fix that

Will see whether I can find more issues this afternoon.

**Comment by smth** [comment]
> Filter dropdowns do not close after selection. Is this by design?

Not by design, as much as by default. I have changed this now though, as I think having them close would be what the user would expect.

> if e.g. the 'audience' filter is selected, and there is no 'type:Stories', could 'type:Stories' be greyed out / removed automatically?

That's not mentioned in the Isotope docs (relevant section [here](https://isotope.metafizzy.co/filtering.html#combination-filters-ui)). Anything is possible, but I'll defer that request to a developer.

> if a menu option in the header is selected, could you remove the black outline box and instead apply the hover animation in green? 

Done

> as @skarampatakis said, could you make the filter dropdowns close after selection?

Done

> on the 'Upload' page, could the images be enlargeable by clicking?

Yes, if we have larger images. Could you supply these? Also a mockup of how'd you'd like that to look (unless you'd just like the image to open in a new tab). 

> some of the tools have false tags, I'll go through them and fix that

Yeah, I assigned those randomly, so will need adjusting by someone who knows what they should be. Similarly, all the links are missing.

**Comment by seegerseeger** [comment]
Ok, the screenshots are attached. For the enlargement, a simple viewer such as [this](https://fengyuanchen.github.io/viewer/) (without the transition animation when changing images) would suffice. 
![describe data 1](https://user-images.githubusercontent.com/9677965/27288999-c0c9c5d2-5508-11e7-937d-62e994a9d5e9.png)
![describe data 2](https://user-images.githubusercontent.com/9677965/27288998-c0c74cf8-5508-11e7-91d0-6e881f680bae.png)
![provide metadata 1](https://user-images.githubusercontent.com/9677965/27289000-c0cd4d10-5508-11e7-9fb9-22058342a370.png)
![provide metadata 2](https://user-images.githubusercontent.com/9677965/27289001-c0dfd714-5508-11e7-95d5-96b0f8d8c3dd.png)
![upload data](https://user-images.githubusercontent.com/9677965/27289002-c0ee5fe6-5508-11e7-9eea-42b57f526df1.png)

**Comment by smth** [comment]
Thanks @seegerseeger As these are all individual images, it raises the question of how you would like them to relate to the overlapping images. For example:

1. Just show one of the two images when clicked.
2. Show one, but include some navigation to switch between the two.
3. Show both at the same time.
4. Make each individual image clickable.

You suggest that there will be a means of switching between images. Should I take it that you are expecting to be able to navigate through all of the images, once one is enlarged?

**Comment by seegerseeger** [comment]
Exactly! :) after clicking, show one, with navigation to switch between the two. Otherwise, there likely wouldn't be enough detail to see what's going on.

**Comment by smth** [comment]
Sorry, those were meant to be options :) Sounds like you are thinking number 2?

**Comment by seegerseeger** [comment]
Yes, number 2!

**Comment by seegerseeger** [comment]
@smth: one thing I/we forgot is the partner page, could you still add that to the footer? http://openbudgets.eu/about/partners/ thanks!

**Comment by smth** [comment]
Large images and partners link now added.

**Comment by seegerseeger** [comment]
hi @smth, two questions: 
1. I've added the missing icons and updated the tools according to their stakeholder group. Could you pull these changes in the testdeployment? 
2. I've also added colored versions of the icons, could you turn that into a mouseover? I've moved the icons to /img/toolbox (e.g. soccer.svg) and added the colored ones there as well (e.g. soccer-c.svg)

**Comment by smth** [comment]
OK, that's done. Code currently assumes that icons will always be SVGs, the naming convention is consistent, and that the coloured version is in the same location as the monochrome one.

(There are a few images missing.)

**Comment by seegerseeger** [comment]
Hi @smth, 

the OBEU tools made by the tool producing partners are finally ready and available under apps.openbudgets.eu. To link them on the website, I think a new layout/page class has to be created since the url syntax is now e.g. apps.openbugets.eu/upload for the uploader. Could you provide that or let me know how to create one? 
 
A few more things we've noticed:

* the footer is missing the EU logo & disclaimer sentence 'this project has received funding..'
* the social media buttons (twitter, fb, github) have disappeared 

It would be great if you could add those if it's no hassle :)

**Comment by pwalsh** [comment]
@seegerseeger can you provide a requirements/spec for this please (e.g.: exact texts and behaviour you want, screenshots of what is missing, etc), just so we prevent lots of back and forth as @smth is currently working on something else right now and very limited on time.

**Comment by seegerseeger** [comment]
OK I see, Lazaros will take care of the tool integration actually, so there is no need to do that. If Sam is busy I will see that we take care of the footer & social media buttons. So for now, nothing needs to be done from his side, if there should be problems I will report back!

**Comment by seegerseeger** [comment]
thanks @smth, @pwalsh and everyone who contributed!
