### ISSUE TITLE
Frames are barely visible

### ISSUE THREAD

**Issue by chudan** [openbudgets/openbudgets.github.io#5]
Just a detail - frames on the contact page are barely visible, a little bit more of grey would be nice. On the homepage´s top menu are (maybe) unnecessary.

**Comment by cecilaki** [comment]
Hi @smth possible to change the color of the fields borders on the [contact page](http://openbudgets.eu/contact/) to a darker grey?

**Comment by smth** [comment]
Yes, will do.
