### ISSUE TITLE
Reduce max-width in blogposts to increase readability

### ISSUE THREAD

**Issue by seegerseeger** [openbudgets/openbudgets.github.io#7]
Blogposts are very wide, which makes them hard to read. There seems to be a 'posts' class, but I don't really understand the hierarchies between sass and css.

**Comment by smth** [comment]
How about something like this for larger screens?
![post](https://cloud.githubusercontent.com/assets/1375708/17556902/0e96aae8-5f0d-11e6-9717-b0816f33de83.jpg)

and perhaps if we go down that route, we make the header green (with a white version of the logo)

![post2](https://cloud.githubusercontent.com/assets/1375708/17558757/950ba992-5f13-11e6-8d9d-292e6f893b90.jpg)

**Comment by smth** [comment]
@seegerseeger @annafralberts any preferences here, or are you happy for me to just run with it?

**Comment by annafralberts** [comment]
Yes, much better! Like the second version better indeed. 

Thanks and sorry for the late reply

**Comment by smth** [comment]
OK, great. This is now implemented on the staging site http://okfnlabs.org/openbudgetseu-staging/post/2016/06/21/third-greek-national-action-plan-a-new-perspective-for-fiscal-transparency/

**Comment by annafralberts** [comment]
Can you make the text of the blogposts 'outlined'.

**Comment by smth** [comment]
I'm not sure what you mean by "outlined" here. Could you elaborate please?

**Comment by annafralberts** [comment]
Meant left and right 'justified' so that the text appears a bit cleaner.

**Comment by smth** [comment]
Ah OK, can do.

**Comment by smth** [comment]
Done.
